apiVersion: v1
kind: Service
metadata:
  name: juego2d-service
  namespace: devops-ep3
  labels:
    app: juego2d
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: juego2d