name: Pipeline_EP1_DevOps

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar Juego
        run: |
          echo "Compilando archivo Main.java raíz..."
          # Compilamos el archivo que está suelto en la carpeta principal
          javac Main.java
          echo "¡Compilación exitosa!"